#!/usr/bin/env bash
set -euo pipefail

file="src/Clash/RemoteConfig/Lainbo.ini"

sed -i 's/|isp|/|/g' "$file"
sed -i '/^exclude_remarks/a\\nruleset=✈️ 节点选择,https://raw.githubusercontent.com/LeflyChan/Remote-Config/refs/heads/main/src/Clash/List/CustomProxy.list\n\nruleset=💬 AI专用,https://raw.githubusercontent.com/LeflyChan/Remote-Config/refs/heads/main/src/Clash/List/CustomAI.list\n\nruleset=🇺🇸 美国自动,https://raw.githubusercontent.com/LeflyChan/Remote-Config/refs/heads/main/src/Clash/List/America.list\n\nruleset=🇪🇺 欧洲自动,https://raw.githubusercontent.com/LeflyChan/Remote-Config/refs/heads/main/src/Clash/List/Europe.list\n\nruleset=🇯🇵 日本自动,https://raw.githubusercontent.com/LeflyChan/Remote-Config/refs/heads/main/src/Clash/List/Japan.list\n\nruleset=🎵 RYM专用,https://raw.githubusercontent.com/LeflyChan/Remote-Config/refs/heads/main/src/Clash/List/RYM.list\n\nruleset=📚 EH专用,https://raw.githubusercontent.com/LeflyChan/Remote-Config/refs/heads/main/src/Clash/List/EH.list\n\nruleset=🔗 无需代理,https://raw.githubusercontent.com/LeflyChan/Remote-Config/refs/heads/main/src/Clash/List/CustomDirect.list' "$file"
sed -i '/^custom_proxy_group=💬 AI专用/a\custom_proxy_group=🎵 RYM专用`select`[]🇯🇵 日本自动`[]🇸🇬 狮城自动`[]🇺🇸 美国自动`[]🇨🇳 台湾自动`[]🇪🇺 欧洲自动`(?i)^((?!实验性|日用|San ?Jose|(?<!白)俄罗斯|莫斯科|圣彼得堡|[新]?西伯[力利]亚|哈巴罗夫斯克|Russia|Moscow|Petersburg|Siberia|\\bRU[S]?\\b|港|Hong ?Kong|\\b(?:HK[G]?|HKT|HKBN|HGC|WTT|CMI)\\b|澳门|Macao|\\bCTM\\b|朝鲜|North ?Korea|古巴|Cuba|伊朗|Iran|叙利亚|Syria|乌克兰|Ukraine|委内瑞拉|Venezuela|🇭🇰|🇲🇴|🇷🇺|🇰🇵|🇨🇺|🇮🇷|🇸🇾|🇺🇦|🇻🇪).)*$' "$file"
sed -i '/^custom_proxy_group=📲 Telegram/a\custom_proxy_group=📚 EH专用`select`[]🇯🇵 日本自动`[]🇸🇬 狮城自动`[]🇺🇸 美国自动`[]🇨🇳 台湾自动`[]🇪🇺 欧洲自动`(?i)^((?!实验性|日用|San ?Jose|(?<!白)俄罗斯|莫斯科|圣彼得堡|[新]?西伯[力利]亚|哈巴罗夫斯克|Russia|Moscow|Petersburg|Siberia|\\bRU[S]?\\b|港|Hong ?Kong|\\b(?:HK[G]?|HKT|HKBN|HGC|WTT|CMI)\\b|澳门|Macao|\\bCTM\\b|朝鲜|North ?Korea|古巴|Cuba|伊朗|Iran|叙利亚|Syria|乌克兰|Ukraine|委内瑞拉|Venezuela|🇭🇰|🇲🇴|🇷🇺|🇰🇵|🇨🇺|🇮🇷|🇸🇾|🇺🇦|🇻🇪).)*$' "$file"
